spring:
  datasource:
    url: ${DEPARTMENT_DB_URL}
    username: ${DEPARTMENT_DB_USERNAME}
    password: ${DEPARTMENT_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DEPARTMENT_DDL_AUTO:validate}

eureka:
  client:
    service-url:
      defaultZone: ${DEPARTMENT_EUREKA_URL}
