spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:localhost}:27017/workforce_document_db
      auto-index-creation: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://10.0.0.12:8761/eureka/}

gcp:
  bucket:
    name: ${GCP_BUCKET_NAME:my-default-local-bucket}
