spring:
  datasource:
    url: ${EMPLOYEE_DB_URL}
    username: ${EMPLOYEE_DB_USERNAME}
    password: ${EMPLOYEE_DB_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${EMPLOYEE_EUREKA_URL}
