spring:
  datasource:
    url: ${EMPLOYEE_DB_URL:jdbc:mysql://localhost:3306/workforce_employee_db?createDatabaseIfNotExist=true}
    username: ${EMPLOYEE_DB_USERNAME:root}
    password: ${EMPLOYEE_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EMPLOYEE_EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health
